adm/urls.py
#django
from django.urls import path
from django.contrib.auth.decorators import login_required


from . import views

app_name = "adm"
urlpatterns = [
    #extension: /adm/
    path("", login_required(views.IndexView.as_view()), name ="index"),
    path("profile/<int:pk>", login_required(views.ProfileDetailView.as_view()), name ="profile"),
    path("profile/update/<int:pk>", login_required(views.ProfileUpdateBasicView.as_view()), name ="profile_update"),
    path("profile/checkdetails/<int:pk>", login_required(views.CheckProfile), name="check_details"),
    path("profile/update/detail/<int:pk>", login_required(views.ProfileUpdateOtherView.as_view()), name ="profile_update_others"),
    path('profile/password_change/',login_required(views.PasswordChangeView.as_view()), name='password_change'),
    path('profile/password-change/done/', login_required(views.PasswordChangeDoneView.as_view()), name='password_change_done'),
    path("profile/update/done", login_required(views.ProfileUpdatedView.as_view()), name ="profile_updated"),
    path("settings", login_required(views.SettingsView.as_view()), name ="settings"),
    path("settings/create", login_required(views.SettingsCreateView.as_view()), name ="settings_create"),
    path("settings/update/<int:pk>", login_required(views.SettingsUpdateView.as_view()), name ="settings_update"),
    path("ads", login_required(views.AdsView.as_view()), name ="ads"),
    path("ads/why", login_required(views.WhyView.as_view()), name ="why"),
    path("ads/why/update/<int:pk>", login_required(views.WhyUpdateView.as_view()), name ="why_update"),
    path("ads/why/delete/<int:pk>", login_required(views.WhyDeleteView.as_view()), name ="why_delete"),
    path("ads/banner/secondary/<int:pk>", login_required(views.SecondaryBannerView.as_view()), name ="secondary_banner"),
    path("ads/banner/update/<int:pk>", login_required(views.BannerUpdateView.as_view()), name ="banner_update"),
    path("ads/banner/delete/<int:pk>", login_required(views.BannerDeleteView.as_view()), name ="banner_delete"),
    path("parcel", login_required(views.ParcelView.as_view()), name ="parcel"),
    path("parcel/update/<int:pk>", login_required(views.ParcelUpdateView.as_view()), name ="parcel_update"),
    path("parcel/delete/<int:pk>", login_required(views.ParcelDeleteView.as_view()), name ="parcel_delete"),
    path("new_parcel", login_required(views.NewParcelView.as_view()), name ="new_parcel"),
    path("banner/upload", login_required(views.UploadBanner), name ="upload_banner"),
    path("category", login_required(views.CategoryView.as_view()), name ="category"),
    path("category/create/", login_required(views.Category_Create), name ="category_create"),
    path("category/delete/<int:pk>", login_required(views.CategoryDeleteView.as_view()), name ="category_delete"),
    path("category/banner/view/<int:pk>", login_required(views.CategoryBanner), name ="modal_preview_category"),
    path("category/update/<int:pk>", login_required(views.CategoryUpdateView.as_view()), name ="category_update"),
    path("subcategory/create/", login_required(views.SubCategory_Create), name ="subcategory_create"),
    path("subcategory/update/<int:pk>", login_required(views.SubCategoryUpdateView.as_view()), name ="subcategory_update"),
    path("subcategory/delete/<int:pk>", login_required(views.SubCategoryDeleteView.as_view()), name ="subcategory_delete"),
    path("products", login_required(views.ProductView.as_view()), name ="products"),
    path("products/create", login_required(views.CreateProductView.as_view()), name ="products_create"),
    path("products/update/<int:pk>", login_required(views.UpdateProduct.as_view()), name ="products_update"),
    path("products/delete/<int:pk>", login_required(views.ProductDelete.as_view()), name ="products_delete"),
    path("orders", login_required(views.OrdersView.as_view()), name ="orders"),
    path("orders/add/<int:order>", login_required(views.OrdersView.as_view()), name ="orders_add"),
    path("orders/detail/<int:pk>", login_required(views.OrdersDetailView.as_view()), name ="orders_detail"),
    path("orders/status/update/<int:pk>", login_required(views.OrdersStatusUpdateView.as_view()), name ="orders_status_update"),
    path("orders/delete/<int:pk>", login_required(views.OrderDeleteView.as_view()), name ="orders_delete"),
    path("users", login_required(views.UsersView.as_view()), name ="users"),
    path("users/new", login_required(views.UsersCreateView), name ="new_user"),
    path("users/delete/<int:pk>", login_required(views.UsersDeleteView.as_view()), name ="users_delete"),
    path("users/detail/<int:pk>", login_required(views.UserDetailView), name ="users_detail"),
    path("payment/mercadopago", views.MercadoPagoView, name ="mercadopago"),


]

comics_pyc/urls.py
#Django
from django.contrib import admin
from django.urls import path, include,re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required


#Local
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='home'),
    path('login', views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('adm/', include('adm.urls')),
    path('all_products', views.AllProductsView.as_view(), name="all_products"),
    path('contact/<int:pk>', views.ContactView.as_view(), name="contact"),
    path('user/create', views.CreateUser, name="create_user"),
    path('categories/<int:pk>', views.CategoriesView.as_view(), name='categories'),
    path('subcategory/<int:pk>', views.SubcategoryView, name='subcategory'),
    path('details/<int:pk>', views.DetailView.as_view(), name='details'),
    path('cart', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>', views.addCart, name='add'),
    path('cart/remove/<int:product_id>', views.removeCart, name='remove'),
    path('cart/decrement/<int:product_id>', views.decrementCart, name='decrement'),
    path('checkout/', login_required(views.CheckoutView), name='checkout'),
    path('checkout/payment', login_required(views.paymentView), name='payment'),
    path('checkout/successfully', login_required(views.SuccessfullyView), name="successfully"),
    path('checkout/failed', login_required(views.FailedView), name="failed"),
    path('checkout/pending', login_required(views.PendingView), name="pending"),
    path('orders/<int:pk>', login_required(views.OrdersView), name="orders"),
    path('tyc', views.TyCView.as_view(), name="tyc"),

]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$',serve,{
            'document_root': settings.MEDIA_ROOT
        })
        ]

adm/views.py
#Django
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render,redirect
from django.urls import reverse_lazy, reverse
from django.views.generic.base import TemplateView
from django.views.generic import CreateView,UpdateView,DetailView,DeleteView, ListView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.views import redirect_to_login, PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views
from django.views.decorators.csrf import csrf_exempt

#Local
from .models import Banner,Category,SubCategory, Product, Cart, Order, Parcel, UserDetail, Region, Settings, Status, SecondaryBanner, Why
from .forms import AddNewBanner, AddCategory, AddSubCategory, AddProduct, CreateParcel, OrderStatus, SettingsForm, ProfileDetailForm, ProfileForm, CreateUser2, SecondaryBannerForm, WhyForm
from comics_pyc.functions import Show
from comics_pyc.credentials import Credentials

#python
import requests
import mercadopago
import json

class UserAccessMixin(PermissionRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if(not self.request.user.is_authenticated):
            return redirect_to_login(self.request.get_full.path(),
            self.get_login_url(),self.get_redirect_field_name())

        if not self.has_permission():
            return redirect('login')
        return super(UserAccessMixin, self).dispatch(request,*args,*kwargs)

class ProfileDetailView(PermissionRequiredMixin, DetailView):
    permission_required = "is_staff"
    template_name = 'adm/profile.html'
    model = User

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data_settings'] = Show.settings_data()
        return context

class ProfileUpdateBasicView(PermissionRequiredMixin,UpdateView):
    model = User
    success_url = reverse_lazy('adm:profile')
    template_name = 'adm/settings_update.html'
    form_class = ProfileForm
    permission_required = 'is_staff'
    success_url = reverse_lazy('adm:profile_updated')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data_settings'] = Show.settings_data()
        return context

class ProfileUpdatedView(PermissionRequiredMixin, TemplateView):
    template_name = 'adm/profile_updated.html'
    permission_required = 'is_staff'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data_settings'] = Show.settings_data()
        return context

def CheckProfile(request, pk):
    try:
        UserDetail.objects.get(pk=pk)
        return HttpResponseRedirect(reverse('adm:profile_update_others', args=(pk,)))
    except UserDetail.DoesNotExist:
        user = User.objects.get(pk=pk)
        try:
            region = Region.objects.get(pk=1)
        except Region.DoesNotExist:
            Region.objects.create(name="")
            region = Region.objects.get(pk=1)
        
        try:
            parcel = Parcel.objects.get(pk=1)
        except Parcel.DoesNotExist:
            Parcel.objects.create(id=1,name="")
            parcel = Parcel.objects.get(pk=1)
        UserDetail.objects.create(user=user, interior_number=0, region=region, parcel=parcel)
        return HttpResponseRedirect(reverse('adm:profile_update_others', args=(pk,)))

class ProfileUpdateOtherView(PermissionRequiredMixin,UpdateView):
    permission_required = 'is_staff'
    model = UserDetail
    form_class = ProfileDetailForm
    template_name = 'adm/settings_update.html'
    success_url = reverse_lazy('adm:profile_updated')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data_settings'] = Show.settings_data()
        return context

class PasswordChangeView(PermissionRequiredMixin, PasswordChangeView):
    template_name = 'adm/password_change_form.html'
    permission_required = "is_staff"
    success_url = reverse_lazy('adm:password_change_done')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data_settings'] = Show.settings_data()
        return context

class PasswordChangeDoneView(PasswordChangeDoneView):
    permission_required = "is_staff"
    template_name = 'adm/password_change_done.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data_settings'] = Show.settings_data()
        return context

class SettingsView(UserAccessMixin,TemplateView):
    permission_required = "is_staff"
    model = Settings
    template_name = 'adm/settings.html'
    
    try:
        settings = Settings.objects.get(pk=1)
    except:
        settings = ''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = self.settings
        context['data_settings'] = Show.settings_data()
        return context

class SettingsCreateView(UserAccessMixin,CreateView):
    permission_required = "is_staff"
    model = Settings
    form_class = SettingsForm
    template_name = 'adm/settings_create.html'
    success_url = reverse_lazy('adm:settings')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data_settings'] = Show.settings_data()
        return context

class SettingsUpdateView(UserAccessMixin,UpdateView):
    permission_required = "is_staff"
    model = Settings
    form_class = SettingsForm
    template_name = 'adm/settings_update.html'
    success_url = reverse_lazy('adm:settings')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data_settings'] = Show.settings_data()
        return context

class IndexView(UserAccessMixin,TemplateView):
    template_name = 'adm/index.html'
    permission_required = 'is_staff'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data_settings'] = Show.settings_data()
        return context

class SecondaryBannerView(UserAccessMixin,UpdateView):
    template_name = 'adm/secondary_banner.html'
    permission_required = 'is_staff'
    model = SecondaryBanner
    form_class = SecondaryBannerForm
    success_url = reverse_lazy('adm:ads')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data_settings'] = Show.settings_data()
        return context

class ParcelView(UserAccessMixin,ListView):
    permission_required = 'is_staff'
    template_name = 'adm/parcel.html'
    model = Parcel

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data_settings'] = Show.settings_data()
        return context

class NewParcelView(UserAccessMixin,CreateView):
    permission_required = 'is_staff'
    template_name = 'adm/new_parcel.html'
    model = Parcel
    form_class = CreateParcel
    success_url = reverse_lazy('adm:parcel')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data_settings'] = Show.settings_data()
        return context

class ParcelUpdateView(UserAccessMixin,UpdateView):
    permission_required = 'is_staff'
    template_name = 'adm/parcel_update.html'
    model = Parcel
    form_class = CreateParcel
    success_url = reverse_lazy('adm:parcel')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data_settings'] = Show.settings_data()
        return context

class ParcelDeleteView(UserAccessMixin,DeleteView):
    permission_required = 'is_staff'
    model = Parcel
    success_url = reverse_lazy('adm:parcel')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data_settings'] = Show.settings_data()
        return context

class AdsView(UserAccessMixin,ListView):
    template_name = 'adm/ads.html'
    permission_required = 'is_staff'
    model = Banner
    form = AddNewBanner

    def get_ads():
        ads = SecondaryBanner.objects.all()
        return ads
    
    def get_why():
        why = Why.objects.all()
        return why

    def disable(self):
        count_ads = Banner.objects.all().count()
        if count_ads >= 3:
            disable = True
        else:
            disable = False
        return disable

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form']=self.form
        context['data_settings'] = Show.settings_data()
        context['secondary_banner'] = AdsView.get_ads()
        context['why'] = AdsView.get_why()
        context['disabled'] = self.disable()
        return context

class BannerUpdateView(UserAccessMixin,UpdateView):
    template_name = 'adm/ads_update.html'
    permission_required= 'is_staff'
    model = Banner
    form_class = AddNewBanner
    success_url = reverse_lazy('adm:ads')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data_settings'] = Show.settings_data()
        return context

class BannerDeleteView(UserAccessMixin, DeleteView):
    template_name = 'adm/banner_delete.html'
    model = Banner
    success_url = reverse_lazy('adm:ads')
    permission_required = 'is_staff'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['data_settings'] = Show.settings_data()
        return context

def UploadBanner(request):
    if request.method == "POST":
        # Fetching the form data
        uploadedFile = request.FILES["uploadedFile"]
        name = request.POST["name"]

        # Saving the information in the database
        document = Banner(
            name = name,

adm/templates/adm/ads.html
{% extends 'adm/base.html' %}

{% block body %}

<h1>Publicidad</h1>
<h2>Banner Publicitario</h2>
{% if disabled == True %}
  <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#staticBackdrop" aria-controls="staticBackdrop" disabled>Agregar Banner</button>
{% else %}
  <button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#staticBackdrop" aria-controls="staticBackdrop">Agregar Banner</button>
{% endif %}
<br>
<div class="offcanvas offcanvas-start" data-bs-backdrop="static" tabindex="-1" id="staticBackdrop" aria-labelledby="staticBackdropLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="staticBackdropLabel">Agregar banner</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <div>
        <form action="{% url 'adm:upload_banner' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <p>Se recomienda en formato PNG medidas 1000px x 500px</p>
            <input type="submit" class="btn btn-primary" value="Subir">
        </form>

      </div>
    </div>
  </div>
  
  <table class="table">
    <thead>
      <th>Nombre</th>
      <th>Banner</th>
      <th>Acciones</th>
    </thead>
    <tbody>
      {% for detail in object_list %}
      <tr>
        <td>{{detail.name}}</td>
        <td><img src="/media/{{detail.uploadedFile}}" alt="{{detail.name}}" width="100"></td>
        <td>        
          <a href="{% url 'adm:banner_update' detail.pk %}"><i class="bi bi-pencil"></i></a>
          <a href="{% url 'adm:banner_delete' detail.pk %}"><i class="bi bi-trash3"></i></a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <h2>Anuncios</h2>
    <table class="table">
      <thead>
        <th>Nombre</th>
        <th>Banner</th>
        <th>Acciones</th>
      </thead>
      <tbody>
        {% for detail in secondary_banner %}
        <tr>
          <td>{{detail.name}}</td>
          <td><img src="/media/{{detail.uploadedFile}}" alt="{{detail.name}}" width="100"></td>
          <td>        
            <a href="{% url 'adm:secondary_banner' detail.pk %}"><i class="bi bi-pencil"></i></a>
            <a href="{% url 'adm:secondary_banner' detail.pk %}"><i class="bi bi-trash3"></i></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

  <h2>Por qué comprar</h2>
  <a href="{% url 'adm:why' %}" class="btn btn-primary">Agregar Motivo</a>
  <br>
  {% if why %}
  <br>
    <table class="table">
      <thead>
        <th>Motivo</th>
        <th>Acciones</th>
      </thead>
      <tbody>
        
          {% for detail in why %}
            <tr>
              <td>{{detail}}</td>
              <td>        
                <a href="{% url 'adm:why_update' detail.pk %}"><i class="bi bi-pencil"></i></a>
                <a href="{% url 'adm:why_delete' detail.pk %}"><i class="bi bi-trash3"></i></a>
              </td>
            </tr>
          {% endfor %}
  
      </tbody>
    </table>
    {% else %}
    <br>
      <div class="alert alert-danger" role="alert">
        Aun no estableces por qué te deben comprar, <a href="{% url 'adm:why' %}" class="alert-link">crea un motivo ahora</a> 
      </div>
    {% endif %}
{% endblock body %}

adm/templates/adm/ads_update.html
{% extends 'adm/base.html' %}
{% block body %}
<h1>Editar {{object.name}}</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Editar" class="btn btn-primary">
</form>

{% endblock body %}

adm/templates/adm/banner_delete.html
{% extends 'adm/base.html' %}
{% block body %}
<form method="post">
    <h1>Eliminar {{object}}</h1>
    {% csrf_token %}
    <br>
    <p>Estás seguro que deseas eliminar "{{ object }}"?</p>
    {{ form }}
    <br>
    <input type="submit" class="btn btn-primary" value="Confirmar">
    <a href="{% url 'adm:category' %}" class="btn btn-secondary">Cancelar</a>
</form>
{% endblock body %}

adm/templates/adm/category.html
{% extends 'adm/base.html' %}
{% load static %}

{% block body %}
<h1>Categorias</h1>
<h2>Categorias Principales</h2>
<button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#category" aria-controls="staticBackdrop">Nueva Categoria</button>
<div class="offcanvas offcanvas-start" data-bs-backdrop="static" tabindex="-1" id="category" aria-labelledby="staticBackdropLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="staticBackdropLabel">Nueva Categoria</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <div>
        <form action="{% url 'adm:category_create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <p>Se recomienda en formato PNG medidas 400 x 240</p>
            <input type="submit" class="btn btn-primary" value="Crear">
        </form>

      </div>
    </div>
  </div>
{% if categories %}

<table class="table table-striped table-hover">
   <thead>
    <th>Categoria</th>
    <th>Banner</th>
    <th>#</th>
   </thead>
   <tbody>
    {% for category in categories %}
    <tr>
        <td>{{category.name}}</td>
        <td>
            <a href="#" onclick="abrir_modal_edicion('{% url 'adm:modal_preview_category' category.pk %}')">
                <img src="/media/{{category.banner}}" alt="{{category.name}}" width="50">
            </a>
        </td>
        <td>
          <a href="{% url 'adm:category_update' category.pk %}"><i class="bi bi-pencil"></i></a>
          <a href="{% url 'adm:category_delete' category.pk %}"><i class="bi bi-trash3"></i></a>
        </td>
    </tr>
    {% endfor %}
   </tbody>
  </table>
{% else %}
<div class="alert alert-danger mt-3" role="alert">
    No hay Categorias disponibles, puedes crear una haciendo click <a data-bs-toggle="offcanvas" href="#category" role="button" aria-controls="offcanvasExample" class="alert-link">Aquí</a>
  </div>
{% endif %}


<h2>Sub Categorias</h2>
<button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#subcategory" aria-controls="staticBackdrop">Nueva Sub Categoria</button>
<div class="offcanvas offcanvas-start" data-bs-backdrop="static" tabindex="-1" id="subcategory" aria-labelledby="staticBackdropLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="staticBackdropLabel">Nueva Sub Categoria</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <div>
        <form action="{% url 'adm:subcategory_create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form_subcategory.as_p}}
            <p>Se recomienda en formato PNG medidas 400 x 240</p>
            <input type="submit" class="btn btn-primary" value="Crear">
        </form>

      </div>
    </div>
  </div>
{% if subcategories %}

<table class="table table-striped table-hover">
   <thead>
    <th>Categoria</th>
    <th>Banner</th>
    <th>#</th>
   </thead>
   <tbody>
    {% for category in subcategories %}
    <tr>
        <td>{{category.category}} / {{category.name}}</td>
        <td>
            <a href="#" onclick="abrir_modal_edicion('{% url 'adm:modal_preview_category' category.pk %}')">
                <img src="/media/{{category.banner}}" alt="{{category.name}}" width="50">
            </a>
        </td>
        <td>
          <a href="{% url 'adm:subcategory_update' category.pk %}"><i class="bi bi-pencil"></i></a>
          <a href="{% url 'adm:subcategory_delete' category.pk %}"><i class="bi bi-trash3"></i></a>
        </td>
    </tr>
    {% endfor %}
   </tbody>
  </table>
{% else %}
<div class="alert alert-danger mt-3" role="alert">
    No hay Sub Categorias disponibles, puedes crear una haciendo click <a data-bs-toggle="offcanvas" href="#subcategory" role="button" aria-controls="offcanvasExample" class="alert-link">Aquí</a>
  </div>
{% endif %}

{% endblock body %}

adm/templates/adm/category_update.html
{% extends 'adm/base.html' %}
{% load static %}
{% block body %}
<h1>Editar {{object.name}}</h1>

      <form enctype="multipart/form" method="POST">

            {% csrf_token %}
            {{ form.as_p }}

        <input type="submit" class="btn btn-primary" value="Actualizar">
        <a href="{% url 'adm:category' %}" class="btn btn-secondary">Volver</a>
    </form>

  {% endblock body %}

adm/templates/adm/order_detail_template.html
{% load humanize %}
<h1>Detalles del pedido #{{object.id}}
    <a href="{% url 'adm:orders' %}" class="btn btn-warning">Volver</a>
    </h1>
    <div class="d-flex">
        <div>
            <h2>General</h2>
            <div class="m-3">
                <h5>Fecha de Creación:</h5>
                <p>{{object.creation_date}}</p>
            
                <h5>Estado:</h5>
                <div class="d-flex">
                    <p class="badge text-bg-{{badge}}">{{object.status}}</p>
                    <a href="{% url 'adm:orders_status_update' object.id %}" class="ms-3">Cambiar Estado</a>
                </div>
                
                <h5>Cliente:</h5>
                <div class="d-flex">
                    <div class="p-3">
                        <h6>Nombre:</h6>
                        <p>
                        {{object.customer.first_name}} {{object.customer.last_name}} 
                        (#{{object.customer.id}} - {{object.customer.email}})
                        </p>
                    </div>
                    <div class="p-3">
                        <h6>Teléfono:</h6>
                        <p>{{object.customer.userdetail.phone}}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="m-3">
            <h2>Detalles del Envio</h2>
            <div class="d-flex">
                <div class="p-3">
                    <h6>Dirección:</h6>
                    <p>{{object.customer.userdetail.address}}</p>
                </div>
                <div class="p-3">
                    <h6>Casa/depto/nºinterior:</h6> 
                    <p>{{object.customer.userdetail.interior_number}}</p>
                </div>
                <div class="p-3">
                    <h6>Comuna:</h6>
                    <p>{{object.customer.userdetail.comuna}}</p>
                </div>
                <div class="p-3">
                    <h6>Región:</h6>
                    <p>{{object.customer.userdetail.region}}</p>
                </div>
            </div>
        </div>
    </div>
    
    
    
    
    <h2>Detalles del Pedido</h2>
    <h5>Productos</h5>
    <div class="d-flex">
        <table class="table table-striped table-hover">
        <thead>
            <th>Artículo</th>
            <th>Costo</th>
            <th>Cantidad</th>
            <th>Total</th>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <th><img src="/media/{{product.product.image}}" alt="{{product.product.name}}" width="50">
                     {{product.product.name}}</th>
                    <th>${{product.product.price|intcomma}}</th>
                    <th>x {{product.quantity}}</th>
                    <th>${{product.subtotal|intcomma}}</th>
                    
                </tr>
            {% endfor %} 
            <tr>
                <td colspan="2"></td>
                <td>Total:</td>
                <td>${{object.total|intcomma}}</td>
            </tr>
        </tbody>
        </table>
    </div>